test/routing: add tracing and make new test pass using more hops
The failures are due to the node not sending the NodeApproaval message.
The first failure is due to the proxy having disconnected from the
node when it split, while the node is not yet aware of the new sections.
As a result we drop the initial message: Clarify with updated trace.

Because it seems related to Route+Ack, tweak the test to not fail by
adding an extra node and so extra hop. (2x slow down for that test).

test mock_crust::simultaneous_joining_nodes_three_section_with_one_ready_to_split ... FAILED
After 866 iterations: Some([3187588240, 2344477088, 740780660, 3411451473])
panicked at 'Should be full node: [d6ea74..]', tests/mock_crust/mod.rs:272:5

After 866 2233: Some([2069996267, 3391318504, 4213380458, 3258736215])
After 866 15874: Some([1527131325, 3342965328, 26773507, 727610073])
After 866 11150: Some([1179589766, 2639846223, 4064746714, 3209835625])

Soak test:
Run simultaneous_joining_nodes_three_section_with_one_ready_to_split for
25'000 times in parallel.