fix/chain: Ensure we provide the correct proof for Prefix authority
multiple_joining_nodes failed with seed after 1000 iterations:
Some([3916974036, 312593624, 819085280, 2177096903])
panicked at 'Elder(550551..(01)) Untrusted SignedRoutingMessage {
content: RoutingMessage { src: Section(name: c00000..), dst: PrefixSection(prefix: Prefix(0)),
content: NeighbourInfo(EldersInfo(prefix: Prefix(11), ...}, prev_hash_len: 1, version: 16)) },

The problem is we pick the knowledge of the first item in the destination
in this case 00, and so 01 does not have enough info.

Ensure we handle prefix authority correctly by taking as much of the
proof as needed by any section covered by the prefix.

Test:
Verify seed fixed.
Soak test + clippy